sonar.organization=milhamridhop
sonar.projectKey=MIlhamRidhoP_TA-ssdlc-devops-akademik
sonar.sources=src
sonar.tests=tests
sonar.exclusions=node_modules/**,migrations/**,scripts/**
sonar.sourceEncoding=UTF-8
